name: book_me
description: 智慧閱讀推薦應用程式

# 應用程式版本資訊
publish_to: 'none' # 移除此行如果您希望發布到 pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI 圖示
  cupertino_icons: ^1.0.2
  
  # HTTP 請求 - Google Books API
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Dart 代碼分析規則
  flutter_lints: ^2.0.0

# Flutter 設定
flutter:
  uses-material-design: true

  assets:
    - assets/fitness_app/
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700